services:

  gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"

  pedidos:
    build: ./pedidos-service
    ports:
      - "3001:3001"

  pagamentos:
    build: ./pagamentos-service
    ports:
      - "3002:3002"

  estoque:
    build: ./estoque-service
    ports:
      - "3003:3003"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: pedidosveloz
    ports:
      - "5432:5432"