name: CI-CD

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar Dependências
        run: |
          cd api-gateway
          npm install

      - name: Verificação
        run: echo "Build realizado com sucesso"

      - name: Docker Build
        run: |
          docker build -t api-gateway ./api-gateway